/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CookieAlert {
        "message": string;
    }
}
declare global {
    interface HTMLCookieAlertElement extends Components.CookieAlert, HTMLStencilElement {
    }
    var HTMLCookieAlertElement: {
        prototype: HTMLCookieAlertElement;
        new (): HTMLCookieAlertElement;
    };
    interface HTMLElementTagNameMap {
        "cookie-alert": HTMLCookieAlertElement;
    }
}
declare namespace LocalJSX {
    interface CookieAlert {
        "message"?: string;
        "onAccepted"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "cookie-alert": CookieAlert;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cookie-alert": LocalJSX.CookieAlert & JSXBase.HTMLAttributes<HTMLCookieAlertElement>;
        }
    }
}
